### ISSUE TITLE
AttributeError: partially initialized module 'cv2' has no attribute 'gapi_wip_gst_GStreamerPipeline' (most likely due to a circular import)

### ISSUE THREAD

**Issue by adsian** [OpenGVLab/InternGPT#16]
![image](https://github.com/OpenGVLab/InternGPT/assets/34738478/a87bc7b8-a2f1-4bad-97d0-2378bcc450f1)

**Comment by iskewedI** [comment]
Try: 
`pip uninstall opencv-python
pip uninstall opencv-contrib-python
pip uninstall opencv-contrib-python-headless`

Then:
`pip3 install opencv-contrib-python==4.5.5.62`

(*inside the virtual environment*)

**Comment by liu-zhy** [comment]
You can refer to https://github.com/opencv/opencv-python/issues/749.

The most probable reason may be multiple OpenCV instances installed on your system.

You can try the method provided by @iskewedI or refer to https://stackoverflow.com/questions/72706073/attributeerror-partially-initialized-module-cv2-has-no-attribute-gapi-wip-gs.

**Comment by adsian** [comment]
> Try:
> 
> > pip uninstall opencv-python
> > pip uninstall opencv-contrib-python
> > pip uninstall opencv-contrib-python-headless
> 
> Then:
> 
> > pip3 install opencv-contrib-python==4.5.5.62
> 
> (_inside the virtual environment_)

tianks, it resovled
