### ISSUE TITLE
Please updated the wechat QR code.

### ISSUE THREAD

**Issue by yanhl0** [OpenGVLab/InternGPT#31]

**Comment by liu-zhy** [comment]
I have already updated the wechat QR code. 

Is this [Wechat QR code](https://github.com/Zeqiang-Lai/DragGAN/assets/26198430/962435d4-8858-4032-ab76-f8ae1e6b18c9)  expired?

**Comment by romain130492** [comment]
> I have already updated the wechat QR code.
> 
> Is this [Wechat QR code](https://github.com/Zeqiang-Lai/DragGAN/assets/26198430/962435d4-8858-4032-ab76-f8ae1e6b18c9) expired?

THe QR code is still expired @liu-zhy
