### ISSUE TITLE
install on docker error

### ISSUE THREAD

**Issue by adsian** [OpenGVLab/InternGPT#32]
![1686140557271](https://github.com/OpenGVLab/InternGPT/assets/34738478/ea2cae74-8e02-4a1b-b06c-dd8dfd2277c9)

and also cannot open https://127.0.0.1:7862/ in browser

**Comment by liu-zhy** [comment]
It seems you access the wrong port. You can try https://0.0.0.0:7860 because we have mapped the port in `InternGPT/docker/InternGPT_CN/docker-compose.yml`
@G-z-w please take a look for this issue.
