### ISSUE TITLE
How to request the download URL for the llama weights?

### ISSUE THREAD

**Issue by dizhenx** [OpenGVLab/InternGPT#45]
How to request the download URL for the llama weights?

**Comment by G-z-w** [comment]
You need to request a form for the download url from Meta (see [here]((https://github.com/facebookresearch/llama))). Once you have the download url, paste it into `PRESIGNED_URL=""` at [third-party/llama_download.sh](third-party/llama_download.sh).

**Comment by G-z-w** [comment]
You need to request a form for the download url from Meta (see [here](https://github.com/facebookresearch/llama)). Once you have the download url, paste it into `PRESIGNED_URL=""` at [third-party/llama_download.sh](third-party/llama_download.sh).
