### ISSUE TITLE
能发下微信群二维码嘛？之前的过期了

### ISSUE THREAD

**Issue by yysirs** [OpenGVLab/InternGPT#46]

**Comment by liu-zhy** [comment]
Thanks for your attention! We have updated WeChat QR code:
https://github.com/OpenGVLab/InternGPT/assets/13723743/a1ec29e4-f35a-43c1-84d7-d191ce466a75

**Comment by yysirs** [comment]
超过了200人，需要邀请才能入群🤣

**Comment by yysirs** [comment]
已经加入了，感谢

**Comment by guxiaojing** [comment]
能拉我入群吗（♪(･ω･)ﾉ）

**Comment by guxiaojing** [comment]
能再发一下微信群二维码嘛（Thanks♪(･ω･)ﾉ）

**Comment by liu-zhy** [comment]
If you want to join our WeChat group, please scan the following QR Code to add our assistant as a Wechat friend:
https://user-images.githubusercontent.com/26198430/253845075-e3f0807f-956a-474e-8fd2-1f7c22d73997.png
