### ISSUE TITLE
OpenAI key not accepted

### ISSUE THREAD

**Issue by atxcowboy** [OpenGVLab/InternGPT#6]
After the demo server spins up, I cannot login to OpenAI with an api key. I confirmed with another app that the api key is good.
In the GUI I see:

Incorrect key, please input again

The console just logs:
===>logging in

How can I debug this further?

**Comment by liu-zhy** [comment]
Hi, thanks for your attention! We are aware of this bug and we have two options to fix this issue for you:

1) You can run export `export OPENAI_API_KEY="{Your OpenAI Key}"` in the terminal before starting app.py and then run `python -u app.py --load "HuskyVQA_cuda:0,SegmentAnything_cuda:0,ImageOCRRecognition_cuda:0" --port 3456 -d`. The `-d` flag means the debug mode and langchain will read the OpenAI key from the environment variable.

2) You can pull the latest code from the main branch which has fixed the bug when logging in.

We apologize for this problem. We appreciate your suggestions and PRs!

**Comment by liu-zhy** [comment]
By the way, If you use `-d` flag, you needn't input the OpenAI key every time when logging in and just clicking the login button is ok.

**Comment by atxcowboy** [comment]
Thanks for the clarification!
